# .streamlit/secrets.toml
TT_CLIENT_ID = "848482f6-b7d8-4351-806b-3ce1492b8187"
TT_CLIENT_SECRET = "d486426ff14b98526ada9e890692ac4e1f035924"
TT_REDIRECT_URI = "https://tastytrade-app-7zahykmrhfdggm9hthosaw.streamlit.app/"
